# @package _global_
project:
  path: /workspaces/torchmtc/out/netruns
  name_prefix: torchmtc
  version: 0.01
data:
  path: /.datasets
  name_dataset: mnist
  epochs: 20
  batch_size: 60
  num_triplet_train: 10000
  num_triplet_val: 5000
  workers: 3
trainer:
  lr: 0.0001
  momentun: 0.9
  cuda: True
  gpu: 0
  parallel: True
  arch: preactresembnet18
  loss: hinge
  opt: adam
  scheduler: step
  numclass: 10
  numchannels: 3
  image_size: 32
  dim: 32
  margin: 1.0
  finetuning: True
checkpoint:
  resume: chk000000.pth.tar
  verbose: True
  print_freq: 10
  snapshot: 5
